Sys.setlocale("LC_TIME", "English")
project1<-read.table("household_power_consumption.txt",header=TRUE,sep=";",colClasses=c("character","character",rep("numeric",7)),fill=TRUE,na.strings="?")
project1<-subset(project1,Date=="1/2/2007"|Date=="2/2/2007")
project1$Date<-as.Date(project1$Date,format="%d/%m/%Y")
project1$DateTime<-paste(project1$Date,project1$Time)
project1$DateTime<-strptime(project1$DateTime,format=("%Y-%m-%d %H:%M:%S")) 
par(xaxp=c(0,6,3),yaxp=c(0,1200,6))
hist(project1$Global_active_power,breaks=12,col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.copy(png,"plot1.png")
dev.off()
