Sys.setlocale("LC_TIME", "English")
project1<-read.table("household_power_consumption.txt",header=TRUE,sep=";",colClasses=c("character","character",rep("numeric",7)),fill=TRUE,na.strings="?")
project1<-subset(project1,Date=="1/2/2007"|Date=="2/2/2007")
project1$Date<-as.Date(project1$Date,format="%d/%m/%Y")
project1$DateTime<-paste(project1$Date,project1$Time)
project1$DateTime<-strptime(project1$DateTime,format=("%Y-%m-%d %H:%M:%S")) 
axis(1,at=1:3,lab=c("Thu","Fri","Sat"))
plot(project1$DateTime,project1$Global_active_power,xlab="",ylab="Global Active Power(kilowatts)",type="l")
dev.copy(png,"plot2.png")
dev.off()